server:
  port: 7102

spring:
  application:
    name: consul-client
  profiles:
    active: dev  # 环境 dev|test|prod
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

#springboot2.0 的actuator配置项为：
management:
  endpoint:
    shutdown:
          enabled: true # 开始POST shutdown
  endpoints:
    web:
#      base-path: "/" #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点

info: # 应用信息 /actuator/info 显示信息
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    profiles: ${spring.profiles.active}
    java:
      source: '@java.version@'
      target: '@java.version@'