server:
  port: 7010

spring:
  application:
    name: zuul-server
  profiles:
    active: dev

app:
  ticket:
    filter:
      enabled: false # 开启ticket过滤

# 注册服务
eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 20
  client:
#    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒
#    registry-fetch-interval-seconds: 5

# 发现服务
#feign:
#  hystrix:
#    enabled: true # 开启断路器

#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false

# 路由设置
zuul:
  #prefix: /techouse #为zuul设置一个公共的前缀
  #ignoredServices: '*'
#  add-host-header: true
  routes:
#    baidu:
#      path: /baidu/**
#      url: http://www.baidu.com/
    user-path:  # 用户服务
      path: /user/**
      serviceId: user-service
#      stripPrefix: true
#    payment-path: # 配置中心
#      path: /payment/**
#      serviceId: payment-service
#      stripPrefix: true