# tomcat
server:
  port: 7020
  servlet:
    context-path: /

spring:
  application:
    name: security-service
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mindasoft.cloud.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5 #间隔多久去拉取服务注册信息，默认为30秒
    instance-info-replication-interval-seconds: 10  # 实例信息变化报送间隔 30s
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5    # 续eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-expiration-duration-in-seconds: 10 # Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒 EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效
    #需要增加下面配置，告诉注册中心访问路径变化
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /
    metadataMap:
      version: @version@
      group: example-service-group
      region: dev

#springboot2.0 的actuator配置项为：
management:
  endpoint:
    shutdown:
          enabled: true # 开始POST shutdown
  endpoints:
    web:
#      base-path: "/" #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
info: # 应用信息 /actuator/info 显示信息
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    profiles: ${spring.profiles.active}
    java:
      source: '@java.version@'
      target: '@java.version@'

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout:  20000   # 响应超时 20s
  ConnectTimeout:  15000   # 连接超时 15s
  ServerListRefreshInterval: 2000  # ribbon缓存时间

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #设置超时熔断时间，默认1000(1s)
      circuitBreaker:
        requestVolumeThreshold: 3 # 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
        sleepWindowInMilliseconds: 15000 # 触发短路的时间值，默认5000，则当触发 circuit break 后的5000毫秒内都会拒绝request 也就是5000毫秒后才会关闭circuit。
        forceOpen: false # 强制打开熔断器，如果打开这个开关，那么拒绝所有request，默认false
        forceClosed: false # 强制关闭熔断器 如果这个开关打开，circuit将一直关闭且忽略，默认false